# Custom Language File for Launcher Customizer

[ejs.app]
title = "MonkeCraft Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/Fayorg/MonkeCraft-Launcher"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/gMT468uGg5"

[ejs.settings]
sourceGithubLink = "https://github.com/Fayorg/MonkeCraft-Launcher"
supportLink = "https://github.com/Fayorg/MonkeCraft-Launcher/issues"

[ejs.welcome]
welcomeHeader = "WELCOME TO MONKECRAFT"
welcomeDescription = ""
